name: Say Yes Quickly
favicon: null
layout_spectrum: 0.8541025903541595
typography_spectrum: 0.5304459892213345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09133362350985408
  lightness: 0.7150006976444274
  saturation: 0.40909079601988196
  rhythmicContrast: 0.055783828953281045
purpose: []
